# action.yml
name: 'Dbmate Action'
branding:
  icon: 'archive'
  color: 'gray-dark'
description: 'Run Dbmate database migration tool'
inputs:
  version:
    description: 'Dbmate version'
    required: false
    default: latest
  command:
    description: 'Dbmate command to run'
    required: false
    default: '--help'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/amacneil/dbmate:${{ inputs.version }}'
  args:
    - ${{ inputs.command }}
